development:
  adapter: postgresql
  host: localhost
  database: mymobade
  username: mymobade
  password: mma

test:
  adapter: postgresql
  host: localhost
  database: mymobade
  username: mymobade
  password: mma

